spring.application.name=storedsystemmanagement
server.port=8080

# Dùng localhost và trỏ đích danh vào SQLEXPRESS
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=stored_system_db;encrypt=true;trustServerCertificate=true;

# Tài khoản sa và mật khẩu bạn vừa đổi lúc nãy (nhớ check lại mật khẩu cho đúng nhé)
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cho phép Spring Boot nặn ra bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true